src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_resto;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="bigint")
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="module", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=Menu::class, mappedBy="resto")
     */
    private $menus;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="author")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $specialite;




    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->menus = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->libelle)){
            $slugify = new Slugify();
            $this->libelle = $slugify->slugify($this->libelle);
        }
    }

    public function getIdResto(): ?int
    {
        return $this->id_resto;
    }

    public function setIdResto(int $id_resto): self
    {
        $this->id_resto = $id_resto;

        return $this;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setModule($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getModule() === $this) {
                $image->setModule(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Menu[]
     */
    public function getMenus(): Collection
    {
        return $this->menus;
    }

    public function addMenu(Menu $menu): self
    {
        if (!$this->menus->contains($menu)) {
            $this->menus[] = $menu;
            $menu->setResto($this);
        }

        return $this;
    }

    public function removeMenu(Menu $menu): self
    {
        if ($this->menus->removeElement($menu)) {
            // set the owning side to null (unless already changed)
            if ($menu->getResto() === $this) {
                $menu->setResto(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(?string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }




}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Restaurant;
use Doctrine\DBAL\Types\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     * @param string $label
     * @param string $placeholder
     * @param string $options
     * @return array
     */
    private function getConfiguration($label , string $placeholder, $options = []){
        return array_merge([
            'label' => $label,
            'attr' => [ 'placholder' => $placeholder]
        ], $options);
    }
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('libelle', TextType::class, $this->getConfiguration("Libelle","Libelle"))
            ->add('speciality', TextType::class, $this->getConfiguration("Spécialité","spécialité"))
            ->add('telephone', TextType::class, $this->getConfiguration("Téléphone","téléphone"))
            ->add('Add Modele', SubmitType::class)
            ->add('livreurs',EntityType::class, array(
                'class' => 'RestoBundle\Entity\Emplacement',
                'choice_label'=>'adresse',
                'expanded'=>true,
                'multiple'=>true));
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantsController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\CategorieRepository;
use App\Repository\MenuRepository;
use App\Repository\PlatsRepository;
use App\Repository\RestaurantRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

class RestaurantsController extends AbstractController
{
    /**
     * index des restaurants
     * @Route("/restaurants/", name="resto_list", methods={"GET","HEAD"})
     */
    public function index(RestaurantRepository $repos, SessionInterface $session): Response
    {
        // $repos = $this->getDoctrine()->getRepository(Restaurant::class);
        dump($session);
        $resto = $repos->findAll();
        return $this->render('restaurants/index.html.twig', [
            'restos' => $resto,
        ]);
    }

    /**
     * Permet d'afficher un restaurant a partie de son nom
     * @Route ("/restaurants/{libelle}", name="show_resto")
     * @return Response
     */
    public function show($libelle, RestaurantRepository $repos, MenuRepository $menu, PlatsRepository $plat, CategorieRepository $cat): Response
    {
        // trouver un restaurant a partirss d'une libelle
        $resto = $repos->findOneByLibelle($libelle);
        $menus = $menu->findAll($menu);
        $cats = $cat->findAll($cat);
        $plats = $plat->findAll();
        return $this->render('restaurants/show.html.twig',
            ['resto' => $resto,
                'menu' =>$menus,
                'cats' => $cats,
                'plat' => $plats
            ] );

    }

    /**
     * @Route("/restaurants", name="restaurants_search")
     * @return Response
     */
    //Recherche Resto
    public function search(Request $request, RestaurantRepository $repos): Response{
        $resto = $repos->findAll();
        if($request->getMethod("POST")){
            $em = $this->getDoctrine()->getManager();
            $motcle=$request->get('input_recherche');
            $query=$em->createQuery(
                "SELECT m FROM App\Entity\Restaurants m WHERE m.libelle LIKE '".$motcle."%'"
            );
            $resto=$query->getResult();
        }
        return $this->render('restaurants/index.html.twig',
            [
                'restau'=>$resto
            ]);
    }

    /**
     * @Route("/restaurants/list", name="restaurants")
     */
    public function showAll(RestaurantRepository $reposs, SessionInterface $session): Response
    {
        $resto = $reposs->findAll();
        return $this->render('restaurants/list.html.twig', [
            'restau' => $resto,
        ]);
    }

//ajouter un resto
    /**
     * Permet d'afficher un restaurant a partie de son nom
     * @Route ("/restaurants/add", name="add_resto")
     * * @return Response
     */
    public function add(Request $request, RestaurantRepository $repos): Response
    {
        $Modele = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $Modele);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Modele);
            $entityManager->flush();
            $this->addFlash('success', "Les données du restaurant ont élé enregistré avec succés !");

        }

        return $this->render('restaurants/add.html.twig',
            array(
                'Form'=>$form->createView()
            ));
    }

// supprimer un resto
    /**
     * Permet d'afficher un restaurant a partie de son nom
     * @Route ("/restaurants/delete/{id}", name="delete_resto")
     */
    public function deleteResto(Request $request, $id , RestaurantRepository $repos): Response
    {
        $resto = $repos->find($id);
        $em= $this->getDoctrine()->getManager();
        if ($resto!==null)
        {
            $em->remove($resto);
            $em->flush();
        }
        else
        {
            throw new NotFoundHttpException("Le restaurant d'id".$id."n'existe pas");
        }

        return $this->redirectToRoute("show_resto");
    }

//Mettre à jour un resto
    /**
     * Permet d'afficher un restaurant a partie de son nom
     * @Route ("/restaurants/update/{id}", name="update_resto")
     */
    public function update(Request $request, $id, RestaurantRepository $repos):Response
    {
        $resto = $repos->find($id);
        $editform = $this->createForm(RestaurantType::class, $resto);
        $editform->handleRequest($request);

        if ($editform->isSubmitted() && $editform->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($resto);
            $em->flush();
            return $this->redirect($this->generateUrl("show_resto"));
        }

        return $this->render('restaurants/update.html.twig',
            [
                'editForm'=>$editform->createView()
            ]);
    }
    public function findAllOrdered()
    {
        $dql = 'SELECT plat FROM Entity\Categorie c, Entity\Plats p where p.';
    }


}

templates/restaurants/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Register {% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<div class="container">
    <div class="row">
        <div class="col-3">&nbsp;</div>

        <div class="col-6">
            <div class="bg-light py-3 px-3">
                <h2>Ajouter Restaurant</h2>
                {{ form_start(Form) }}
                {{ form_widget(Form) }}
                <button type="submit" class="btn btn-success">Ajouter !</button>
                {{ form_end(Form) }}
            </div>
        </div>

    </div>
    {% endblock %}

</div>

templates/restaurants/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos Restaurants!{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            {% for resto in restos %}
                <div class="m-4">
                    <div class="card bg-light mb-3" style="max-width: 20rem;">
                        <div class="card-header"><a href="{{ path('show_resto', {'libelle':resto.libelle}) }}">{{ resto.libelle }}</a></div>
                        <img src="{{ resto.image }}" style="height:200px; width:100%;">
                        <div class="card-body">
                            <h4 class="card-title">Dark card title</h4>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/restaurants/list.html.twig
<h1>Liste des modèles</h1>
<table border="1">
    <tr>
        <td>id</td>
        <td>Libelle</td>
        <td>speciality</td>
        <td>telephone</td>
        <td>Supprimer</td>
        <td>Modifier</td>
    </tr>
    {% for resto in restau %}
        <tr>
            <td>{{ resto.idResto }}</td>
            <td>{{ resto.libelle }}</td>
            <td>{{ resto.specialite}}</td>
            <td>{{ resto.tel}}</td>
            <td><a href="{{ path("delete_resto", {'id' : resto.idResto}) }}" >Supprimer</a> </td>
            <td><a href="{{ path("update_resto", {'id' : resto.idResto}) }}" >Modifier</a> </td>
        </tr>
    {% endfor %}

</table>

templates/restaurants/show.html.twig
{% extends 'base.html.twig' %}
{%  block title %}
{% endblock %}

{% block body %}

 <div class="has-text-centered-touch resto-title" style="background-image: url({{ resto.image }});">
     <div class="container">
         <h1>{{ resto.libelle }}</h1>
     </div>


 </div>
<div class="container">
    <h2>Menu</h2>
    <ul>
    {% for menu in resto.menus %}
    <li>
        {{ menu.
        }}
        <ul>

            {% for plat in menu.plats %}
            <li>

                {{ plat.libelle }}
            </li>
            {% endfor %}
        </ul>
        </li>

    {% endfor %}


</div>

{% endblock %}

templates/restaurants/update.html.twig
<h1>Mise à jour d'un modèle</h1>

<form action="" method="POST">
    {{ form_widget(editForm) }}
    <input type="submit"/>
</form>